"""`map/` holds one generated file, and that is the decision rather than a state.

Decision 38 retired `map/04-agents/`. It had been described in six documents --
`map/README.md`, `PLAN.md` §3.6, `README.md`, `kb/README.md`, `TREE.md`,
`adapters/README.md` -- and generated by nothing: three empty directories and no
`lib/` at all, while `README.md` said it *"already carries the microscope's five
lenses with the gates each one owns."*

**A described artefact that never existed is one step worse than BD's
`INDEX.md`**, which at least has the file and is missing only the generator. So
this test is the guard on the retirement: a future generator that writes a
second, citable rendering of the agent files has to change this test to do it,
which puts a human in the diff.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "map"

#: `manifest.json` is derived and gitignored; `README.md` is the only tracked
#: file. Both are named, so adding either kind of thing is deliberate.
ALLOWED = {"README.md", "manifest.json"}


def test_map_holds_only_the_manifest_and_its_readme():
    present = {p.name for p in MAP.iterdir() if not p.name.startswith(".")}
    unexpected = sorted(present - ALLOWED)
    assert not unexpected, (
        f"map/ gained {unexpected}. Decision 38 retired the 04-agents layer "
        f"because a generated copy of an agent file gives a caller something "
        f"to cite other than the declaration itself. Reintroducing one is a "
        f"design change, not a build artefact.")


def test_no_directories_under_map():
    dirs = sorted(p.name for p in MAP.iterdir() if p.is_dir())
    assert dirs == [], f"map/ has subdirectories again: {dirs}"


def test_only_one_path_under_map_is_ever_constructed():
    """Checked in the code, not only on disk -- an empty folder proves nothing
    about what the next `reindex` will do.

    **Checked as path construction, not as a string search**, and the first
    version got that wrong: grepping for `04-agents` flagged the two docstring
    notes that *record* the retirement, in `adapters/bd_entries.py` and
    `adapters/ms_agents.py`. A rule that forbids naming what was removed makes
    the removal unrecordable, and the next reader then restores the folder for
    want of a reason not to.

    So what is forbidden is narrower and is the thing that matters: code may
    build exactly one path under `map/`, and it is the manifest.
    """
    import re

    sources = (list((ROOT / "librarian").glob("*.py"))
               + list((ROOT / "adapters").glob("*.py"))
               + list((ROOT / "mcp_server").glob("*.py")))
    #: `<something> / "map"` -- the only way a path under this folder is built.
    joins = re.compile(r"""/\s*["']map["']""")
    found = []
    for p in sources:
        for i, line in enumerate(p.read_text(encoding="utf-8").splitlines(), 1):
            if joins.search(line):
                found.append((p.name, i, line.strip()))

    assert found, "nothing builds a path under map/ at all; the manifest moved"
    for name, i, line in found:
        assert "manifest.json" in line, (
            f"{name}:{i} builds a path under map/ that is not the manifest: "
            f"{line}. Decision 38 retired the 04-agents layer because a "
            f"generated copy of an agent file gives a caller something to cite "
            f"other than the declaration itself.")


def test_the_retirement_is_recorded_where_the_folder_was():
    """A deletion with no note reads as an accident, and the next reader
    restores it. `map/README.md` is where they will look."""
    text = (MAP / "README.md").read_text(encoding="utf-8")
    assert "04-agents" in text and "retired" in text.lower()
    assert "decision 38" in text.lower()
